# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release

sudo: false

os:
  - osx

cache: packages

# script:
#     - R CMD build . --no-build-vignettes --no-resave-data --no-manual

warnings_are_errors: false
