# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - release

os:
  - osx

script:
  - R CMD build . #--no-build-vignettes --no-resave-data --no-manual

warnings_are_errors: false
